name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'deployment'  # Your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: "./"   # The root directory where your app is

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies (e.g., Flask)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      # Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover

      # Optional: Build step if needed (Python typically doesn't need this)

      # Deployment to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}    # Use environment variable for the app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use the secret for the publish profile
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"   # Use the app root as the package
